### ISSUE TITLE
Mark unresolved dependencies

### ISSUE THREAD

**Issue by oktomus** [Fanaen/subsystem-mapper#6]
When defining a dependency:
```toml
 [[subsystem.dependency]]
    id = "some_id"
    why = "Because"
```

If the dependency `some_id` is not satisfied (the `toml` file for this is missing), it would be great to show this information in the map. For example:

![image](https://user-images.githubusercontent.com/4656466/75667241-9e01c080-5c77-11ea-9fdf-8e55d901d712.png)
